#!/usr/bin/env python

import os, sys, base64

# I live in .git/assure-tool, and get installed by one of two paths:
# * by publishers, when they run "git-assure setup-publish"
# * by clients, when they run "./setup-assure"
# I am called in multiple ways:
# * "assure-tool setup-publish" (by publishers), to prepare a tree for
#   publishing. This may create a keypair (or ask for an existing signing
#   key), then modify .git/config and add a post-commit hook, then will
#   create and git-add ./setup-assure, then will advise the user to commit
#   and push (to make ./setup-assure available to clients)
# * "assure-tool subscribe" (by setup-assure, run by clients). This modifies
#   .git/config to run during a fetch, and adds the verifying key
# * "assure-tool fetch" (during git-fetch, run by clients). This intercepts
#   the fetch process, examines the remote references, checks their
#   signatures, and allows the fetch to proceed if they are valid.
# * "assure-tool post-commit" (during git-commit's post-commit hook, run by
#   clients). This creates a signature and adds it to the git-notes entry for
#   the new revision.

# note: don't print anything to stdout at the top-level, as stdout is used by
# the proxy when we're in 'fetch' mode. Use stderr instead. It is safe to
# print to stdout form the non-fetch commands, though.

##### == BEGIN ed25519 ==
#<-- ed25519
##### == END ed25519 ==

##### == BEGIN common ==
#<-- common
##### == END common ==

##### == BEGIN setup-client ==
#<-- setup-client
##### == END setup-client ==

# used by both setup-publish and report
post_commit_b64 = """
#<-- post-commit-b64
"""
post_commit = base64.b64decode(post_commit_b64)

##### == BEGIN setup-publish ==
#<-- setup-publish
##### == END setup-publish ==

##### == BEGIN assure-proxy ==
#<-- assure-proxy
##### == END assure-proxy ==

##### == BEGIN sign ==
#<-- sign
##### == END sign ==

##### == BEGIN report ==
#<-- report
##### == END report ==



if sys.argv[1] == "setup-publish":
    setup_publish(sys.argv[2:])
if sys.argv[1] == "setup-client":
    setup_client(sys.argv[2:5])
#if sys.argv[1] == "subscribe":
#    SUBSCRIBE(sys.argv[2:])
if sys.argv[1] == "fetch":
    assure_proxy(sys.argv[2:])
if sys.argv[1] == "post-commit":
    sign(sys.argv[2:])
if sys.argv[1] == "report":
    report(sys.argv[2:])

